BEGIN TRANSACTION;

/* LANGUAGES */
SET IDENTITY_INSERT dbo.languages ON;
INSERT INTO dbo.languages (id, language_code, country_code) VALUES (1,'sv','SE');
INSERT INTO dbo.languages (id, language_code, country_code) VALUES (2,'en','US');
SET IDENTITY_INSERT dbo.languages OFF;
INSERT INTO dbo.languages_detail (language_id, translation_language_id, name) VALUES (1,1,'SE - Svenska');
INSERT INTO dbo.languages_detail (language_id, translation_language_id, name) VALUES (2,1,'US - Engelska');
INSERT INTO dbo.languages_detail (language_id, translation_language_id, name) VALUES (1,2,'SE - Swedish');
INSERT INTO dbo.languages_detail (language_id, translation_language_id, name) VALUES (2,2,'US - English');

/* ADMINISTRATORS */
SET IDENTITY_INSERT dbo.administrators ON;
INSERT INTO dbo.administrators (id, admin_user_name, admin_password, admin_role, email, facebook_user_id, google_user_id) VALUES (1,'Master','1000:BS3ZEKeB3ZOuI1LL:dSYvveOPOyJgAtKb','Administrator','','','');
SET IDENTITY_INSERT dbo.administrators OFF;
INSERT INTO dbo.administrators_detail (administrator_id, language_id, author_name, author_description) VALUES (1,1,'Administrator', '');
INSERT INTO dbo.administrators_detail (administrator_id, language_id, author_name, author_description) VALUES (1,2,'Administrator', '');

/* WEB DOMAINS */
SET IDENTITY_INSERT dbo.web_domains ON;
INSERT INTO dbo.web_domains (id, website_name, domain_name, web_address, front_end_language, back_end_language, custom_theme_id, analytics_tracking_id, facebook_app_id, facebook_app_secret, google_app_id, google_app_secret) VALUES (1,'a-blogsite','localhost','http://localhost:54257',2,2,0,'','','','','');
SET IDENTITY_INSERT dbo.web_domains OFF;

/* WEBSITE SETTINGS */
INSERT INTO dbo.website_settings (id, value) VALUES ('CONTACT-US-EMAIL','');
INSERT INTO dbo.website_settings (id, value) VALUES ('SEND-EMAIL-ADDRESS','');
INSERT INTO dbo.website_settings (id, value) VALUES ('SEND-EMAIL-HOST','');
INSERT INTO dbo.website_settings (id, value) VALUES ('SEND-EMAIL-PASSWORD','');
INSERT INTO dbo.website_settings (id, value) VALUES ('SEND-EMAIL-PORT','');

/* STATIC TEXTS */
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad',1,'Annons');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad_code',1,'Annonskod');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('add',1,'Lägg till');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('added',1,'Tillagd');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad_slot',1,'Annonsplats');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ads',1,'Annonser');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('admin_role',1,'Roll');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('administrator',1,'Administratör');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('administrators',1,'Administratörer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('analytics_tracking_id',1,'Spårnings-ID analytics');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('and',1,'Och');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ascending',1,'Stigande');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('author',1,'Författare');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('author_name',1,'Författarnamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('back_end_language',1,'Backendspråk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('background_image',1,'Bakgrundsbild');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('big',1,'Stor');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('by',1,'Av');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('cancel',1,'Avbryt');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('categories',1,'Kategorier');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('category',1,'Kategori');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('change_frequency',1,'Förändringsfrekvens');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('clear',1,'Rensa');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('comment',1,'Kommentar');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('comments',1,'Kommentarer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('connect',1,'Anslut');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('connected_to',1,'Kopplad till');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('copyright_information',1,'&copy; 2013');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('country_code',1,'Landskod (ISO 3166)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('country_code_short',1,'Landskod');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('custom_design',1,'Egen design');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('custom_images',1,'Egna bilder');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('date',1,'Datum');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('default',1,'Standard');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('delete',1,'Radera');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('descending',1,'Fallande');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('description',1,'Beskrivning');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domain',1,'Domän');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domain_name',1,'Domännamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domains',1,'Domäner');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('download',1,'Ladda ned');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('edit',1,'Ändra');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('email',1,'E-post');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_404',1,'Felsida: 404');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_user_exists',1,'Det finns ingen användare som matchar angivna uppgifter!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_domain_name',1,'Domännamnet får inte inkludera http://, https:// eller www. och får inte vara mer än 100 tecken!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_email_valid',1,'Angiven e-post är inte en giltig adress!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_bad_chars',1,'{0}: består av felaktiga tecken!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_certain_length',1,'{0}: måste bestå av minst {1} tecken och maximalt av {2} tecken!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_language_unique',1,'{0}: måste vara unikt för det valda språket!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_length',1,'{0}: får maximalt bestå av {1} tecken!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_range',1,'{0}: måste vara minst 0 och mindre än {1}!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_required',1,'{0}: måste anges!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_unique',1,'{0}: måste vara unikt!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_invalid_jpeg',1,'Den uppladdade bilden är inte en giltig jpg/jpeg bild!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_general',1,'Felsida: generellt fel');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_invalid_input',1,'Felsida: otillåten indata');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_login',1,'Du har skrivit in fel användarnamn och/eller lösenord!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_select_value',1,'Du måste välja {0}!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_send_email',1,'Det går tyvärr inte att skicka e-post just nu!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('export_to_zip',1,'Exportera alla filer till en zip-fil');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('file_name',1,'Filnamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('file',1,'Fil');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('files',1,'Filer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('forgot',1,'Glömt');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('front_end_language',1,'Frontendspråk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('get',1,'Hämta');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('icon',1,'Ikon');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('id',1,'Id');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('image',1,'Bild');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('images',1,'Bilder');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('import_from_zip',1,'Importera från zip-fil');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('inactive',1,'Inaktiverad');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('keywords',1,'Nyckelord');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language',1,'Språk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language_code',1,'Språkkod (ISO 639-1)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language_code_short',1,'Språkkod');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('languages',1,'Språk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('linkname',1,'Länknamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('list',1,'Lista');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('log_in',1,'Logga in');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('log_out',1,'Logga ut');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('logotype',1,'Logotype');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('main_category',1,'Huvudkategori');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('main_image',1,'Huvudbild');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_file',1,'Mediafil');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_files',1,'Mediafiler');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_type',1,'Mediatyp');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_1',1,'Du har inte behörighet att utföra den här åtgärden.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_2',1,'Är du säker på att du vill ta bort den här posten och alla poster som är kopplade till den här posten?');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_3',1,'Uppladdad(e) bild(er) har en felaktig filändelse, tillåtna filändelser är jpeg och jpg.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_4',1,'Uppladdad(e) bild(er) har en total storlek som överstiger det tillåtna maxvärdet. Komprimera bilden eller ladda upp bilderna styckvis.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_5',1,'Den post som du försökte ta bort kan inte tas bort. Det här beror på att det finns referenser till posten i en eller flera tabeller i databasen.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_1',1,'Behörighet');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_2',1,'Ta bort post');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_3',1,'Bilduppladdning');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_4',1,'Bilduppladdning');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_5',1,'Försök att ta bort post');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('meta_description',1,'Metabeskrivning');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('mobile',1,'Mobil');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_comments',1,'Mina kommentarer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_pages',1,'Mina sidor');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_posts',1,'Mina poster');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_ratings',1,'Mina betyg');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('name',1,'Namn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('new',1,'Ny');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('no_choice',1,'Inget val');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('no_connection',1,'Ingen koppling');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('of',1,'Av');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ok',1,'Ok');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('on',1,'På');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page',1,'Sida');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page_name',1,'Sidnamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page_views',1,'Sidvisningar');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('parent',1,'Överordnad');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('password',1,'Lösenord');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('path',1,'Sökväg');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('post',1,'Post');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('posts',1,'Poster');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('preview',1,'Förhandsgranska');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('priority',1,'Prioritet');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('rating',1,'Betyg');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ratings',1,'Betyg');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('read_more',1,'Läs mer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('register',1,'Registrera dig');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('relation',1,'Relation');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('resources',1,'Resurser');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('restore_to_default',1,'Återställ till standard');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('save',1,'Spara');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('search',1,'Sök');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('search_result',1,'Sökresultat');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('send',1,'Skicka');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('settings',1,'Inställningar');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('show',1,'Visa');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('sitemap',1,'Webbplatskarta');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('small',1,'Liten');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('sort',1,'Sortera');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('source',1,'Källa');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('start_page',1,'Startsidan');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_page',1,'Statisk sida');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_pages',1,'Statiska sidor');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_text',1,'Statisk text');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_texts',1,'Statiska texter');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('target',1,'Mål');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('template',1,'Mall');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('text',1,'Text');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('theme',1,'Tema');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('title',1,'Titel');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('toggle_fullscreen',1,'Växla helskärmsläge');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('translate',1,'Översätt');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('translated',1,'Översatt');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('undo',1,'Ångra');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('update',1,'Uppdatera');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('updated',1,'Uppdaterad');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('upload_files',1,'Ladda upp filer');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('upload_main_image',1,'Bild, 1 mb jpg|jpeg (1:1)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('url',1,'Länk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('user_details',1,'Användaruppgifter');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('user_name',1,'Användarnamn');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('votes',1,'Röster');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('web_address',1,'Webbadress');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('weblink',1,'Webblänk');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('weblinks',1,'Webblänkar');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad',2,'Ad');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad_code',2,'Ad code');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('add',2,'Add');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('added',2,'Added');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ad_slot',2,'Ad slot');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ads',2,'Ads');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('admin_role',2,'Role');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('administrator',2,'Administrator');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('administrators',2,'Administrators');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('analytics_tracking_id',2,'Analytics tracking id');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('and',2,'And');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ascending',2,'Ascending');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('author',2,'Author');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('author_name',2,'Author name');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('back_end_language',2,'Backend language');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('background_image',2,'Background image');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('big',2,'Big');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('by',2,'By');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('cancel',2,'Cancel');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('categories',2,'Categories');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('category',2,'Category');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('change_frequency',2,'Change frequency');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('clear',2,'Clear');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('comment',2,'Comment');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('comments',2,'Comments');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('connect',2,'Connect');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('connected_to',2,'Connected to');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('copyright_information',2,'&copy; 2013');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('country_code',2,'Country code (ISO 3166)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('country_code_short',2,'Country code');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('custom_design',2,'Custom design');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('custom_images',2,'Custom images');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('date',2,'Date');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('default',2,'Default');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('delete',2,'Delete');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('descending',2,'Descending');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('description',2,'Description');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domain',2,'Domain');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domain_name',2,'Domain name');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('domains',2,'Domains');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('download',2,'Download');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('edit',2,'Edit');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('email',2,'Email');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_404',2,'Error: 404');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_user_exists',2,'There is no user that matches the specified information!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_domain_name',2,'The domain name must not include http://, https:// or www. and must not be more than 100 characters!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_email_valid',2,'The specified e-mail is not a valid address!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_bad_chars',2,'{0}: consists of invalid characters!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_certain_length',2,'{0}: must be at least {1} characters and max {2} characters!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_language_unique',2,'{0}: must be unique for the selected language!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_length',2,'{0}: may be up to {1} characters!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_range',2,'{0}: must be at least 0 and less than {1}!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_required',2,'{0}: must be specified!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_field_unique',2,'{0}: must be unique!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_invalid_jpeg',2,'The uploaded image is not a valid jpg/jpeg picture!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_general',2,'Error: general error');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_invalid_input',2,'Error: invalid input');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_login',2,'You have entered a username and/or a password that is invalid!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_select_value',2,'You must select {0}!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('error_send_email',2,'We are unable to send e-mails right now!');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('export_to_zip',2,'Export all files to a zip file');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('file_name',2,'Filename');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('file',2,'File');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('files',2,'Files');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('forgot',2,'Forgot');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('front_end_language',2,'Frontend language');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('get',2,'Get');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('icon',2,'Icon');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('id',2,'Id');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('image',2,'Image');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('images',2,'Images');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('import_from_zip',2,'Import from zip-file');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('inactive',2,'Inactive');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('keywords',2,'Keywords');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language',2,'Language');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language_code',2,'Language code (ISO 639-1)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('language_code_short',2,'Language code');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('languages',2,'Languages');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('linkname',2,'Linkname');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('list',2,'List');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('log_in',2,'Log in');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('log_out',2,'Log out');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('logotype',2,'Logotype');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('main_category',2,'Main category');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('main_image',2,'Main image');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_file',2,'Mediafile');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_files',2,'Mediafiles');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('media_type',2,'Media type');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_1',2,'You do not have permission to perform this action.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_2',2,'Are you sure that you want to remove this post and all posts related to this post?');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_3',2,'Uploaded image(s) have an invalid file extension, allowed extensions are jpg and jpeg.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_4',2,'Uploaded image(s) have a total size that exceeds the allowable maximum. Compress the image or upload the images individually.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_message_5',2,'The item you tried to delete can not be deleted. This is because there are references to the record in one or more tables in the database.');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_1',2,'Authorization');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_2',2,'Remove item');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_3',2,'Image upload');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_4',2,'Image upload');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('message_box_title_5',2,'Attempt to delete item');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('meta_description',2,'Metadescription');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('mobile',2,'Mobile');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_comments',2,'My comments');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_pages',2,'My pages');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_posts',2,'My posts');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('my_ratings',2,'My ratings');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('name',2,'Name');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('new',2,'New');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('no_choice',2,'No choice');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('no_connection',2,'No connection');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('of',2,'Of');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ok',2,'Ok');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('on',2,'On');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page',2,'Page');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page_name',2,'Pagename');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('page_views',2,'Pageviews');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('parent',2,'Parent');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('password',2,'Password');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('path',2,'Path');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('post',2,'Post');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('posts',2,'Posts');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('preview',2,'Preview');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('priority',2,'Priority');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('rating',2,'Rating');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('ratings',2,'Ratings');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('read_more',2,'Read more');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('register',2,'Register');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('relation',2,'Relation');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('resources',2,'Resources');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('restore_to_default',2,'Restore to default');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('save',2,'Save');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('search',2,'Search');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('search_result',2,'Search result');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('send',2,'Send');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('settings',2,'Settings');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('show',2,'Show');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('sitemap',2,'Sitemap');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('small',2,'Small');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('sort',2,'Sort');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('source',2,'Source');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('start_page',2,'Startpage');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_page',2,'Static page');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_pages',2,'Static pages');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_text',2,'Static text');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('static_texts',2,'Static texts');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('target',2,'Target');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('template',2,'Template');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('text',2,'Text');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('theme',2,'Theme');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('title',2,'Title');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('toggle_fullscreen',2,'Toggle fullscreen');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('translate',2,'Translate');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('translated',2,'Translated');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('undo',2,'Undo');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('update',2,'Update');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('updated',2,'Updated');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('upload_files',2,'Upload files');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('upload_main_image',2,'Image, 1 mb jpg|jpeg (1:1)');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('url',2,'Url');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('user_details',2,'User details');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('user_name',2,'Username');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('votes',2,'Votes');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('web_address',2,'Web address');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('weblink',2,'Weblink');
INSERT INTO dbo.static_texts (id, language_id, value) VALUES ('weblinks',2,'Weblinks');

/* STATIC PAGES */
SET IDENTITY_INSERT dbo.static_pages ON;
INSERT INTO dbo.static_pages (id, connected_to_page, meta_robots) VALUES (1,1,'index, follow');
INSERT INTO dbo.static_pages (id, connected_to_page, meta_robots) VALUES (2,2,'noindex, follow');
INSERT INTO dbo.static_pages (id, connected_to_page, meta_robots) VALUES (3,3,'noindex, follow');
INSERT INTO dbo.static_pages (id, connected_to_page, meta_robots) VALUES (4,4,'noindex, follow');
INSERT INTO dbo.static_pages (id, connected_to_page, meta_robots) VALUES (5,0,'noindex, follow');
SET IDENTITY_INSERT dbo.static_pages OFF;
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (1,1,'Startsidan','Välkommen till a-blogsite.se','Det här är a-blogsite.se, en generell struktur för en hemsida med administrationsgränssnitt och en helt anpassningsbar design.','Det här är a-blogsite, en generell struktur för en hemsida med administrationsgränssnitt och helt anpassningsbar design.','start, hem','default',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (2,1,'Generellt fel','Generellt fel','Det har inträffat ett generellt fel på webbplatsen. Kontakta oss gärna så att vi kan åtgärda det här felet.','Det har inträffat ett generellt fel på webbplatsen. Kontakta oss gärna så att vi kan åtgärda det här felet.','generellt fel','error',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (3,1,'Otillåten indata','Otillåten indata','Du har har angivit otillåtna tecken i en textruta. Det är inte tillåtet att ange html, scripts eller annan kod i textrutor på den här webbplatsen. Gå tillbaka i webbläsaren för att fortsätta fylla i det formulär som du jobbade med.','Du har har angivit otillåtna tecken i en textruta. Det är inte tillåtet att ange html, scripts eller annan kod i textrutor på den här webbplatsen.','otillåten indata','invalid_input',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (4,1,'404','Sidan hittades inte (404)','Den sida som du försökte nå kunde inte hittas.','Den sida som du försökte nå kunde inte hittas.','404','404',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (5,1,'Sekretess','Sekretess','Allmän beskrivning av sekretesspolicyn.','Allmän beskrivning av sekretesspolicyn.','sekretess','sekretess',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (1,2,'Startpage','Welcome to a-blogsite.com','This is a-blogsite.com, a general structure of a website with an administration interface and a fully customizable design.','This is a-blogsite, a general structure of a website with an administration interface and a fully customizable design.','start, home','default',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (2,2,'General error','General error','There has been a general error on the site. Please contact us so we can fix this error.','There has been a general error on the site. Please contact us so we can fix this error.','general error','error',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (3,2,'Invalid input','Invalid input','You have entered invalid characters in a textbox. It is not allowed to enter html, scripts or other code in the textboxes on this site. Go back in your browser to continue filling out the form you were working on.','You have entered invalid characters in a textbox. It is not allowed to enter html, scripts or other code in the textboxes on this site.','invalid input','invalid_input',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (4,2,'404','Page not found (404)','The page that you were trying to reach could not be found.','The page that you were trying to reach could not be found.','404','404',0);
INSERT INTO dbo.static_pages_detail (static_page_id, language_id, link_name, title, main_content, meta_description, meta_keywords, page_name, inactive) VALUES (5,2,'Privacy Policy','Privacy Policy','General description of the privacy policy.','General description of the privacy policy.','privacy policy','privacy_policy',0);

/* EXCECUTE THE TRANSACTION */
COMMIT;
